### ISSUE TITLE
Bind statement does not seem to work in versions of sqlite higher than 0.28.0

### ISSUE THREAD

**Issue by dpotter4** [stainless-steel/sqlite#59]
I have some code that updates a sqlite database which works perfectly with version 0.28.0 of the sqlite crate.

However, if I upgrade to the crate sqlite 0.29.0 and above, I get the following error:

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> src/main.rs:23:12
    |
23  |         db.bind(1,username)?;
    |            ^^^^ - -------- supplied 2 arguments
    |            |
    |            expected 1 argument

Is this a bug in the sqlite crate, or do I need to change the syntax I am using when using the latest versions of this crate?

Many thanks.

I have attached the code that I am using (in a text file to allow upload to git):
[main.txt](https://github.com/stainless-steel/sqlite/files/10294438/main.txt)

**Comment by IvanUkhov** [comment]
Hello! Yes, this is correct. There was a breaking API change in between versions. The new one takes a tuple in this case: `bind((1, username))`. Please take a look at the examples in the readme:

https://github.com/stainless-steel/sqlite
